# Generated by Django 4.1.6 on 2023-02-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('numero', models.PositiveSmallIntegerField(null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ruleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta.ruleta')),
            ],
        ),
    ]
